from odoo import fields, models

class StockPicking(models.Model):
    _inherit = 'stock.picking'
    _description = "Stock Picking Inheritance for Product Return"

    return_order = fields.Many2one(
        'sale.return',
        string="Source Return Order",
        help="Links this picking to the original return order for source delivery.")
    return_order_pick = fields.Many2one(
        'sale.return',
        string="Return Order (Generated)",
        help="Links this generated return picking back to the original return order.")
    return_order_picking = fields.Boolean(
        string="Is Return Picking",
        default=False,
        help="Indicates if this picking is a return picking generated by a return order.")
